/**
 * Core Data Models for EnviroGuard
 *
 * SCAFFOLD: These types are designed to match the real API contracts from PRD
 * PRODUCTION: Sync with backend DynamoDB schema
 *
 * Each type includes:
 * - JSDoc explaining its purpose
 * - Field descriptions for AI tools
 * - Reference to corresponding PRD section
 */

// ===== BASIC TYPES =====

export type LayerType = 'noise' | 'trash' | 'hazards';
export type MetricType = 'noise' | 'fill' | 'hazard';
export type SeverityLevel = 1 | 2 | 3 | 4 | 5;
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type ReportType = 'air_pollution' | 'water_contamination' | 'hazardous_waste' | 'noise_pollution' | 'other';
export type ReportStatus = 'pending' | 'verified' | 'resolved' | 'rejected';

// ===== LOCATION =====

/**
 * Geographic coordinates
 * Used across: stations, reports, user locations
 */
export interface Coordinates {
  latitude: number;
  longitude: number;
}

// ===== SENSOR & STATION DATA =====
// PRD Section 2: Product Overview - Three Data Sources

/**
 * Station (kiosk with sensors)
 * DynamoDB Table: enviroguard-stations (future)
 */
export interface Station {
  id: string;
  name: string;
  location: Coordinates;
  address?: string;
  status: 'active' | 'inactive' | 'maintenance';
  installedAt: string;          // ISO 8601 timestamp
}

/**
 * Sensor reading from a station
 * DynamoDB Table: enviroguard-sensor_readings (future)
 */
export interface SensorReading {
  id: string;
  stationId: string;
  timestamp: string;            // ISO 8601
  noise?: {
    db: number;                 // Decibels
    contributors: string[];     // e.g., ["traffic", "construction"]
  };
  trash?: {
    fillPercent: number;        // 0-100
    severity: SeverityLevel;
  };
  hazards?: {
    type: string;              // e.g., "flooding", "spill"
    severity: SeverityLevel;
  };
}

// ===== MAP DATA =====
// PRD Section 6: Tab 1 - Map

/**
 * Zone data for map display
 * Used in: Map heatmap overlay
 */
export interface ZoneData {
  zoneId: string;
  coordinates: Coordinates;
  risks: {
    noise: {
      level: number;            // dB
      severity: RiskLevel;
      contributors: string[];
    };
    trash: {
      fillLevel: number;        // percentage
      severity: RiskLevel;
      lastCollection: string;   // ISO timestamp
    };
    hazards: {
      type: string;
      severity: RiskLevel;
      value: number;
    };
  };
  aggregatedRisk: RiskLevel;
}

// ===== FORECAST DATA =====
// PRD Section 6: Tab 2 - Health & Alerts

/**
 * Single hourly forecast point
 * From: Prophet ML model (future)
 */
export interface HourlyForecast {
  hour: string;                 // ISO timestamp
  predicted: number;            // Predicted value
  confidence: number;           // 0-1
  min: number;                  // Lower bound
  max: number;                  // Upper bound
}

/**
 * Complete forecast data for a metric
 * API Endpoint: POST /predict-noise or /predict-fill (future)
 */
export interface ForecastData {
  metric: MetricType;
  stationId: string;
  generatedAt: string;
  forecast: HourlyForecast[];   // 24 hours
  summary: {
    peakHour: string;
    peakValue: number;
    avgValue: number;
  };
}

/**
 * Alert generated from threshold breach
 * DynamoDB Table: enviroguard-alerts (future)
 */
export interface Alert {
  id: string;
  userId: string;
  timestamp: string;
  type: MetricType;
  severity: RiskLevel;
  station: {
    id: string;
    name: string;
  };
  message: string;
  actionTaken: 'notification_sent' | 'email_sent' | 'none';
  resolved: boolean;
}

// ===== REPORTS =====
// PRD Section 6: Tab 3 - Report

/**
 * Hazard report submitted by user
 * DynamoDB Table: enviroguard-hazard_reports (future)
 * Includes Claude Vision analysis
 */
export interface Report {
  id: string;
  userId: string;
  type: ReportType;
  title: string;
  description: string;
  location: Coordinates;
  address?: string;
  photos: string[];             // URLs or base64
  createdAt: string;
  status: ReportStatus;
  severity: SeverityLevel;
  // Claude Vision analysis fields
  claudeAnalysis?: {
    type: ReportType;
    severity: SeverityLevel;
    description: string;
    confidence: number;
  };
}

// ===== COMMUNITY =====
// PRD Section 6: Tab 4 - Community

/**
 * Community post or event
 * DynamoDB Table: enviroguard-posts (future)
 */
export interface Post {
  id: string;
  type: 'post' | 'event';
  userId: string;
  userName: string;
  userAvatar?: string;
  content: string;
  images?: string[];
  createdAt: string;
  likes: number;
  commentsCount: number;
  // Event-specific fields
  eventDate?: string;
  eventLocation?: string;
  attendees?: number;
}

/**
 * Advocacy letter generated by Claude
 * Not stored in DB (generated on-demand)
 */
export interface AdvocacyLetter {
  content: string;
  generatedAt: string;
  sensorData: SensorReading[];
  location: string;
  recipient: string;
}

// ===== USER & PROFILE =====
// PRD Section 6: Tab 5 - Profile

/**
 * User profile with health settings
 * DynamoDB Table: enviroguard-users (future)
 */
export interface UserProfile {
  userId: string;
  email: string;
  name: string;
  avatar?: string;
  healthConditions: string[];   // e.g., ["asthma", "COPD"]
  alertThresholds: {
    noisedB: number;            // Alert when noise exceeds this
    binFillPercent: number;     // Alert when bin fill exceeds this
    hazardRadiusM: number;      // Alert for hazards within this radius
  };
  savedLocations: SavedLocation[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Saved location (Home, Work, School)
 */
export interface SavedLocation {
  type: 'Home' | 'Work' | 'School';
  address: string;
  coordinates: Coordinates;
}

// ===== API RESPONSES =====

/**
 * Standard API error response
 */
export interface ApiError {
  error: string;
  message: string;
  statusCode: number;
}

/**
 * Standard API success response
 */
export interface ApiSuccess<T> {
  data: T;
  message?: string;
}
